version: '3'

services:
  db:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_USER=newprojectuser
      - POSTGRES_PASSWORD=newprojectpassword
      - POSTGRES_DB=newprojectdb
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=newproject.settings.dev
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.default
      - .env
    depends_on:
      - db
