version: '3'

services:
  db:
    container_name: newproject_db
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_USER=newprojectuser
      - POSTGRES_PASSWORD=newprojectpassword
      - POSTGRES_DB=newprojectdb
  web:
    container_name: newproject_web
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=newproject.settings.dev
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.default
      - .env
    depends_on:
      - db
